[k8s_cluster]
localhost ansible_connection=local ansible_python_interpreter=/usr/bin/python3

[k8s_cluster:vars]
# Target Kubernetes context / kubeconfig path (defaults to ~/.kube/config if not specified)
# k8s_kubeconfig=~/.kube/config
# k8s_context=docker-desktop
